#define MAX_ATTEMPTS 6

//ASCII ART generated by AI
static const char* HANGMAN_STAGES[] = {
    // Stage 0: Base and gallows only
    "  +---+\n"
    "  |   |\n"
    "      |\n"
    "      |\n"
    "      |\n"
    "      |\n"
    "=========\n",

    // Stage 1: Head added
    "  +---+\n"
    "  |   |\n"
    "  O   |\n"
    "      |\n"
    "      |\n"
    "      |\n"
    "=========\n",

    // Stage 2: Torso added
    "  +---+\n"
    "  |   |\n"
    "  O   |\n"
    "  |   |\n"
    "      |\n"
    "      |\n"
    "=========\n",

    // Stage 3: Left arm added
    "  +---+\n"
    "  |   |\n"
    "  O   |\n"
    " /|   |\n"
    "      |\n"
    "      |\n"
    "=========\n",

    // Stage 4: Right arm added
    "  +---+\n"
    "  |   |\n"
    "  O   |\n"
    " /|\\  |\n"
    "      |\n"
    "      |\n"
    "=========\n",

    // Stage 5: Left leg added
    "  +---+\n"
    "  |   |\n"
    "  O   |\n"
    " /|\\  |\n"
    " /    |\n"
    "      |\n"
    "=========\n",

    // Stage 6: Right leg added (Game Over)
    "  +---+\n"
    "  |   |\n"
    "  O   |\n"
    " /|\\  |\n"
    " / \\  |\n"
    "      |\n"
    "=========\n"
};

char* takeWord(char wordlist[100][50]);
void clearBuffer(void);
void updateStr(char* word_to_guess, char* hidden_word, char character);
void mainFrame(char* hidden_word,int attempts);
void clearScreen(void);
int validateInput(int input);